service: volunteer-app

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

functions: 
  app:  
    handler:  src/api/events/index.handler
    events:
      - http:         ANY /
        cors: true
      - http:         ANY /{proxy+}
        cors: true

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  