service: volunteer-app

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

functions: 
  volunteers:  
    handler:  src/api/index.handler
    events:
      - http:         ANY api
        cors: true
      - http:         ANY /{proxy+}
        cors: true

plugins:
  - serverless-offline
  - serverless-plugin-typescript