export const allConstants = {
  LOGOUT: 'LOGOUT_USER',
  LOGIN: 'LOGIN_USER',
  REGISTER: 'REGISTER_USER',
  SET_PREFERENCES: 'SET_PREFERENCES',
  DELETE_EVENT: 'DELETE_EVENT',
  ADD_EVENT: 'ADD_EVENT',
  UPDATE_EVENTS: 'UPDATE_EVENTS',
  SEARCH_EVENTS: 'SEARCH_EVENTS',
  SET_EVENTS: 'SET_EVENTS',
  SET_ENROLLED_EVENTS: 'SET_ENROLLED_EVENTS'
}